language: php

matrix:
  include:
    - php: 5.5
      env: DB=mysqli
  allow_failures:
    - php: hhvm
  fast_finish: true

env:
  global:
    - EXTNAME="acme/demo"  # CHANGE name of the extension HERE
    - SNIFF="1"            # Should we run code sniffer on your code?
    - IMAGE_ICC="0"        # Should we run icc profile sniffer on your images?
    - PHPBB_BRANCH="develop-ascraeus"

branches:
  only:
    - master
    - develop
    - /^develop-.*$/

install:
  - ls -la "phpBB/ext/$EXTNAME/travis/"
  - travis/prepare-phpbb.sh $EXTNAME $PHPBB_BRANCH
  - ls -la "phpBB/ext/$EXTNAME/travis/"
  - cd ../../phpBB3
  - travis/prepare-extension.sh $EXTNAME $PHPBB_BRANCH
  - travis/setup-phpbb.sh $DB $TRAVIS_PHP_VERSION
  - ls -la "phpBB/ext/$EXTNAME/travis/"

before_script:
  - travis/setup-database.sh $DB $TRAVIS_PHP_VERSION

script:
  - cat "phpBB/ext/$EXTNAME/travis/phing-sniff.sh"
  - ls -la "phpBB/ext/$EXTNAME/"
  - ls -la "phpBB/ext/$EXTNAME/travis/"
  - sh -c "if [ '$SNIFF' != '0' ]; then phpBB/ext/$EXTNAME/travis/phing-sniff.sh $DB $TRAVIS_PHP_VERSION $EXTNAME; fi"
  - sh -c "if [ '$IMAGE_ICC' != '0' ]; then travis/check-image-icc-profiles.sh $DB $TRAVIS_PHP_VERSION; fi"
  - phpBB/vendor/bin/phpunit --configuration phpBB/ext/$EXTNAME/travis/phpunit-$DB-travis.xml --bootstrap ./tests/bootstrap.php
